project:
  type: website
  output-dir: _site

website:
  title: "AAGI Shared Code / Code Commons"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: database/index.qmd
        text: About
      - href: database/dtable.qmd
        text: Explore Database
      - href: database/usage.qmd
        text: Usage and Contributions

format:
  html:
    theme: cosmo
    toc: true
    code-fold: true
    css: assets/styles.scss

execute:
  freeze: auto
