project:
  type: website
  output-dir: _site
  resources:
    - assets

website:
  title: "AAGI Shared Code"
  navbar:
    left:
      - href: database/index.qmd
        text: About
      - href: database/usage.qmd
        text: Usage and Contributions
      - href: database/dtable.qmd
        text: Explore Database


format:
  html:
    theme: cosmo
    toc: true
    code-fold: true
    css: assets/styles.css

execute:
  freeze: auto
